name: Build and Upload Python Package to PyPI if Tagged

on: create

jobs:
  publish-to-pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install wheel
        run: python -m pip install wheel --user
      - name: Install setuptools
        run: python -m pip install setuptools --user
      - name: Build a binary wheel and a source tarball
        run: python setup.py sdist bdist_wheel
      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
