name: Build and Upload Python Package to TestPyPI

on:
  push:
    branches:
      - main

jobs:
  publish-to-test-pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install wheel
        run: python -m pip install wheel --user
      - name: Install setuptools
        run: python -m pip install setuptools --user
      - name: Build a binary wheel and a source tarball
        run: python setup.py sdist bdist_wheel
      - name: Upload to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
